@Tournament_API_HostAddress = https://localhost:7265

GET {{Tournament_API_HostAddress}}/api/tournaments

###

POST {{Tournament_API_HostAddress}}/api/tournaments
Content-Type: application/json

{
  //Tournament
}

###

GET {{Tournament_API_HostAddress}}/api/tournaments/2

###
